# Generated by Django 2.2.3 on 2020-06-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_post_stick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tagColor',
            field=models.CharField(default='#15936f', max_length=20),
        ),
    ]
